namespace FoodOrderSystem.Domain.Model
{
    public enum FailureResultCode
    {
        SessionExpired,
        Forbidden,
        WrongCredentials,
        RequiredFieldEmpty,
        ValueMustNotBeNegative,
        UserDoesNotExist,
        UserAlreadyExists,
        CannotRemoveCurrentUser,
        CuisineDoesNotExist,
        CuisineAlreadyExists,
        PaymentMethodDoesNotExist,
        PaymentMethodAlreadyExists,
        RestaurantHasToHaveAName,
        RestaurantImageNotValid,
        RestaurantMinimumOrderValueTooHigh,
        RestaurantDeliveryCostsTooHigh,
        RestaurantDeliveryTimeBeginTooEarly,
        RestaurantDeliveryTimeEndTooLate,
        RestaurantDeliveryTimeIntersects,
        RestaurantDoesNotExist,
        RestaurantContainsDishCategories,
        RestaurantContainsDishes,
        DishCategoryDoesNotBelongToRestaurant,
        DishCategoryContainsDishes,
        DishDoesNotBelongToDishCategory,
        CannotRemoveCurrentUserFromRestaurantAdmins
    }
}
