name: Continuous Integration

on:
  push:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - uses: actions/cache@v2
        name: Configure npm caching
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/workflows/prettier.yml') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          commit_message: ✨ Prettified Code
          prettier_options: --write .
          only_changed: True
